// KNIHOVNA VÝZNAMŮ KARET (v1.6.2). GENEROVÁNO ze zdrojového souboru
// tarotolasce-vyznamy-karet-KOMPLETNI.md - finální, zakladatelem schválený
// text = jediný zdroj pravdy. Texty jsou 1:1, NIKDY je needitovat ručně
// (akceptace = diff proti zdroji bez odchylky). Bez pomlček.
export type LibraryCard = {
  slug: string; // URL slug (bez diakritiky, kebab-case, např. dvojka-poharu)
  name: string;
  section: string;
  appId: string | null; // id karty v appce (ilustrace); null = bez mapování
  intro: string[]; // úvodní odstavce (obecně o kartě)
  up: string; // odstavec *Vzpřímeně* (vztah/single inline dle zdroje)
  rev: string; // odstavec *Obráceně*
  cta: string; // celá CTA věta DOSLOVA (jméno karty už obsahuje)
};

export const LIBRARY_SECTIONS = ["Velká arkána","Malá arkána: Hole","Malá arkána: Poháry","Malá arkána: Meče","Malá arkána: Pentakly"];

export const CARD_LIBRARY: LibraryCard[] = [
  { slug: "blazen", name: "Blázen", section: "Velká arkána", appId: "blazen",
    intro: ["Blázen je karta číslo nula, začátek ještě předtím, než něco skutečně začne. Na obraze stojí mladík na kraji útesu s pohledem upřeným k nebi, ne pod nohy, jako by mu na tom, kam šlápne, vůbec nezáleželo."],
    up: "*Vzpřímeně* v lásce je Blázen o skoku bez záruk. Pokud jsi ve vztahu, může znamenat chuť oživit hravost, přestat všechno plánovat a dovolit si spontánní gesto, které jste dávno nezažili. Pokud jsi sama, jde o otevřenost novému seznámení bez seznamu požadavků, důvěru, že něco přijde, i když nevíš odkud. Riziko tu je, ale Blázen ho nevnímá jako hrozbu, spíš jako cenu za to být naživu.",
    rev: "*Obráceně* karta upozorňuje na naivitu, nebo na lehkost, která je jen předstíraná. Ve vztahu to bývá unáhlené rozhodnutí, které jste udělali, aniž byste si promysleli důsledky, případně jeden z vás schovává vážné obavy za povrchní veselost. V samostatnosti jde často o strach udělat první krok, maskovaný tvrzením, že vztah stejně „teď neřešíš\".",
    cta: "Chceš vědět, co Blázen znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "mag", name: "Mág", section: "Velká arkána", appId: "mag",
    intro: ["Mág stojí u stolu se všemi čtyřmi živly na dosah ruky, jednu paži zvednutou k nebi, druhou ukazující k zemi. Je to karta o tom, že máš k dispozici všechno potřebné, jen to musíš použít."],
    up: "*Vzpřímeně* v lásce Mág mluví o síle slova. Ve vztahu jde o chvíli, kdy dokážeš přesně pojmenovat, co cítíš a co potřebuješ, a komunikace se stává nástrojem, ne překážkou. Pokud jsi sama, karta ukazuje, že máš teď jistotu a přitažlivost, díky které dokážeš navázat spojení, na kterém ti záleží, stačí jen promluvit první.",
    rev: "*Obráceně* se objevuje nesoulad mezi slovem a činem. Ve vztahu to bývá partner, který slibuje víc, než dělá, nebo ty sama, mluvíš o změně, ale zůstáváš ve starých vzorcích. V samostatnosti karta varuje před manipulativní komunikací někoho, kdo umí mluvit líp, než jedná, a stojí za to všímat si rozdílu mezi slovy a skutky.",
    cta: "Chceš vědět, co Mág znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "veleknezka", name: "Velekněžka", section: "Velká arkána", appId: "veleknezka",
    intro: ["Velekněžka sedí mezi dvěma sloupy, tmavým a světlým, se závojem za zády, který skrývá víc, než ukazuje. Je karta ticha, intuice a věcí, které se teprve mají vyjevit."],
    up: "*Vzpřímeně* radí ve vztahu naslouchat mezi řádky. Něco důležitého zůstává nevyřčené, a je to v pořádku, protože pravda vyjde najevo ve správný čas, ne na povel. Pokud jsi sama, karta zve k důvěře ve vlastní instinkt: víš víc, než si přiznáváš, i když to zatím neumíš vysvětlit rozumem.",
    rev: "*Obráceně* upozorňuje na odpojení od vlastní intuice, nebo na to, že se něco tají, možná i před tebou samotnou. Ve vztahu to bývá pocit, že něco nesedí, ale rozum ti to rozmlouvá. V samostatnosti jde o ignorování varovných signálů, protože srdce chce věřit něčemu jinému, než co napovídá zkušenost.",
    cta: "Chceš vědět, co Velekněžka znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "cisarovna", name: "Císařovna", section: "Velká arkána", appId: "cisarovna",
    intro: ["Císařovna sedí v zahradě plné zralého obilí, obklopená hojností, kterou si nemusí zasloužit, jen ji přijímat. Je to karta péče, smyslnosti a přirozeného růstu."],
    up: "*Vzpřímeně* ve vztahu přináší období blízkosti, něhy a vzájemného sdílení bez tlaku na výkon. Je čas přijímat lásku, ne si ji zasluhovat body navíc. Pokud jsi sama, Císařovna zve k péči o sebe jako o první krok, protože vztah, který přijde, bude odrazem toho, jak se dnes chováš sama k sobě.",
    rev: "*Obráceně* karta varuje před péčí, která se stala povinností. Ve vztahu to bývá žena, která dává mnohem víc, než dostává, a vyčerpává se v roli té, co se stará o všechno. V samostatnosti jde o zanedbávání vlastních potřeb ve prospěch představy, jak by měla „dobrá partnerka\" vypadat, ještě než partner vůbec existuje.",
    cta: "Chceš vědět, co Císařovna znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "cisar", name: "Císař", section: "Velká arkána", appId: "cisar",
    intro: ["Císař sedí na kamenném trůnu zdobeném beraními hlavami, symboly rozhodnosti a vůle. Je to karta struktury, stability a jasně vytyčených hranic."],
    up: "*Vzpřímeně* ve vztahu přináší potřebu jasna: otevřený rozhovor o plánech, závazcích a pravidlech vztah spíš upevní, než naruší. Pokud jsi sama, karta ukazuje, že přitahuješ (nebo bys měla hledat) partnera, který stojí pevně na vlastních nohou, ne toho, kdo hledá oporu právě v tobě.",
    rev: "*Obráceně* se struktura mění v svěrací kazajku. Ve vztahu jde o partnera (nebo o tebe samotnou), který drží vše pod kontrolou přes pravidla a autoritu místo skutečné blízkosti. V samostatnosti karta varuje před hledáním jistoty v přísných kritériích, které nikoho živého nemohou splnit.",
    cta: "Chceš vědět, co Císař znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "veleknez", name: "Velekněz", section: "Velká arkána", appId: "veleknez",
    intro: ["Velekněz sedí mezi dvěma sloupy jako Velekněžka, ale obrácený k lidem, ne do sebe. Je karta tradice, sdílených hodnot a rámce, ve kterém se dá stavět něco trvalého."],
    up: "*Vzpřímeně* ve vztahu jde o shodu na tom, co je pro vás oba důležité: věrnost, budoucnost, společné hodnoty. Je to dobrý čas na rozhovor o závazku. Pokud jsi sama, karta ukazuje touhu po vztahu s jasným rámcem, ne po náhodných setkáních bez směru.",
    rev: "*Obráceně* Velekněz ukazuje tlak dělat věci podle toho, co se sluší, ne podle toho, co skutečně chceš. Ve vztahu to bývá cítěný nátlak k dalšímu kroku (svatba, nastěhování), který nejde od srdce. V samostatnosti karta zve zpochybnit pravidlo o lásce, které jsi převzala od okolí, aniž bys ho sama někdy prověřila.",
    cta: "Chceš vědět, co Velekněz znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "milenci", name: "Milenci", section: "Velká arkána", appId: "zamilovani",
    intro: ["Milenci ukazují muže a ženu nahé před andělem, bez studu a bez masky. Je to karta volby, souladu a autenticity, ne jen romantiky, jak by se na první pohled zdálo."],
    up: "*Vzpřímeně* ve vztahu jde o hluboký soulad hodnot, chvíli, kdy víš, že sis vybrala správně, a nemusíš to nikomu dokazovat. Pokud jsi sama, karta signalizuje spojení, které vzniká z opravdové volby srdce, ne z nutnosti mít někoho po ruce.",
    rev: "*Obráceně* karta ukazuje nerozhodnost mezi dvěma lidmi, nebo mezi tím, co říkáš, a co doopravdy cítíš. Ve vztahu to může být pokušení či nevěra, ale častěji jen nesoulad mezi slovy a činy. V samostatnosti jde o špatnou volbu, kterou srdce dávno vytušilo, ale hlava ji ještě obhajuje.",
    cta: "Chceš vědět, co Milenci znamenají přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "vuz", name: "Vůz", section: "Velká arkána", appId: "vuz",
    intro: ["Vůz táhnou dva sfingy, černá a bílá, každá jiným směrem, a přesto jede rovně. Je to karta vůle, odhodlání a schopnosti udržet směr i uprostřed protichůdných sil."],
    up: "*Vzpřímeně* ve vztahu jde o sílu táhnout situaci kupředu, i když vy dva netáhnete úplně stejným tempem. Rozhodnost dnes pomáhá víc než dohadování. Pokud jsi sama, karta ukazuje, že máš teď energii jít si za tím, co chceš, aktivně, ne čekat, až se něco samo semele.",
    rev: "*Obráceně* se energie mění v přetahování o kontrolu. Ve vztahu to bývá pocit, že jedete každý jinam, a únava z neustálého boje o to, kdo rozhoduje. V samostatnosti jde o rozpolcenost mezi tím, co chceš doopravdy, a tím, co si myslíš, že bys chtít měla.",
    cta: "Chceš vědět, co Vůz znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "sila", name: "Síla", section: "Velká arkána", appId: "sila",
    intro: ["Síla ukazuje ženu, jak jemně zavírá tlamu lva, ne silou, ale klidem. Je to karta o tom, že skutečná síla nekřičí a nebojuje, jen vydrží."],
    up: "*Vzpřímeně* ve vztahu jde o trpělivost a laskavost vůči sobě i partnerovi, i ve chvílích, které tě rozhodí. Zvládáš dnes reagovat s nadhledem místo výbuchu. Pokud jsi sama, karta ukazuje vnitřní klid, díky kterému nepotřebuješ vztah k tomu, aby ses cítila celistvá.",
    rev: "*Obráceně* dochází síla předstírat, že je všechno v pořádku. Ve vztahu to bývá vyčerpání z toho, kolik toho v sobě dusíš, aby byl klid. V samostatnosti jde o pochybnosti o vlastní hodnotě, které tě nutí přijímat víc, než by sis zasloužila.",
    cta: "Chceš vědět, co Síla znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "poustevnik", name: "Poustevník", section: "Velká arkána", appId: "poustevnik",
    intro: ["Poustevník stojí sám na vrcholu hory s lucernou v ruce, světlem, které svítí jen na krok před ním. Je karta ústupu, introspekce a moudrosti, která přichází v tichu."],
    up: "*Vzpřímeně* ve vztahu jde o potřebu prostoru, chvíle sama pro sebe předtím, než uděláš další krok. Není to útěk, je to příprava. Pokud jsi sama, karta ukazuje, že tohle období samoty má smysl, protože tě připravuje na to, co přijde, až budeš připravená.",
    rev: "*Obráceně* se zdravá samota mění v izolaci ze strachu. Ve vztahu jde o stažení se místo řešení, mlčení jako obranu, ne jako klid. V samostatnosti karta varuje, že se možná uzavíráš víc, než je pro tebe dobré, a vyhýbáš se lidem, kteří by ti mohli pomoct.",
    cta: "Chceš vědět, co Poustevník znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "kolo-stesti", name: "Kolo štěstí", section: "Velká arkána", appId: "kolo-stesti",
    intro: ["Kolo štěstí se točí samo, poháněné silami, které nemáš plně pod kontrolou. Je to karta cyklů, obratů a chvil, kdy se něco změní, ať jsi na tom pracovala, nebo ne."],
    up: "*Vzpřímeně* ve vztahu jde o obrat k lepšímu, který přichází zdánlivě odnikud: usmíření, nové pochopení, šťastná náhoda. Pokud jsi sama, karta signalizuje, že se blíží změna, možná setkání, které nečekáš, přesně ve chvíli, kdy na to přestaneš tlačit.",
    rev: "*Obráceně* se kolo zasekává na stejném místě. Ve vztahu jde o opakující se hádku nebo vzorec, který se vrací znovu a znovu, dokud ho někdo vědomě nepřeruší. V samostatnosti karta ukazuje pocit, že se pořád scházíš se stejným typem člověka, se stejným výsledkem.",
    cta: "Chceš vědět, co Kolo štěstí znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "spravedlnost", name: "Spravedlnost", section: "Velká arkána", appId: "spravedlnost",
    intro: ["Spravedlnost drží váhy v jedné ruce a meč v druhé, symboly rovnováhy a jasného rozhodnutí bez příkras. Je to karta upřímnosti, i té nepohodlné."],
    up: "*Vzpřímeně* ve vztahu jde o poctivé zhodnocení situace, včetně vlastního podílu na tom, co se děje. Rozhodnutí, ke kterému dnes dojdeš, bude fér, i když nemusí být příjemné. Pokud jsi sama, karta radí posuzovat potenciálního partnera podle skutků, ne podle toho, jak moc si přeješ, aby byl ten pravý.",
    rev: "*Obráceně* se objevuje nevyváženost, kterou jsi dlouho přehlížela. Ve vztahu to bývá pocit, že jedna strana dává víc, nebo že se řeší jen to, co chce ten hlasitější z vás dvou. V samostatnosti jde o nespravedlnost vůči sobě, třeba v podobě přísnějšího soudu nad vlastními city, než by sis zasloužila.",
    cta: "Chceš vědět, co Spravedlnost znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "viselec", name: "Viselec", section: "Velká arkána", appId: "viselec",
    intro: ["Viselec visí hlavou dolů na stromě, ale výraz má klidný, skoro osvícený. Je to karta pauzy, obráceného pohledu a moudrosti, která přichází, jen když se přestaneš snažit."],
    up: "*Vzpřímeně* ve vztahu jde o prospěšnost zastavení se: než zareaguješ, zkus se na situaci podívat z druhé strany. Někdy se věc pohne právě tím, že ji na chvíli necháš být. Pokud jsi sama, karta ukazuje, že čekání teď není promarněný čas, ale nutná zastávka před dalším krokem.",
    rev: "*Obráceně* se zdravá pauza mění v uvíznutí. Ve vztahu jde o čekání na něco, co se dávno mělo pohnout, nebo o obětování se za vztah, který ti to nevrací. V samostatnosti karta varuje před sebeobětováním, které už dávno přestalo být volbou a stalo se návykem.",
    cta: "Chceš vědět, co Viselec znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "smrt", name: "Smrt", section: "Velká arkána", appId: "smrt",
    intro: ["Smrt je jedna z nejvíc obávaných karet balíčku, a přitom málokdy znamená to, čeho se lidé nejvíc bojí. Zobrazuje kostlivce na bílém koni, ne jako trest, ale jako součást přirozeného koloběhu."],
    up: "*Vzpřímeně* v lásce jde téměř vždy o proměnu, ne o doslovný konec. Ve vztahu to bývá uzavření staré role či staré hádky, aby mohla vzniknout nová kapitola mezi vámi dvěma. Pokud jsi sama, karta ukazuje konec období, které tě drželo na místě, a otevírá prostor pro něco, co ještě nemá tvar.",
    rev: "*Obráceně* Smrt ukazuje odpor ke změně, která je stejně nevyhnutelná. Ve vztahu jde o lpění na něčem, co už neroste, ze strachu, ze závislosti, nebo z pohodlí. V samostatnosti karta varuje, že se držíš vzorců či lidí z minulosti způsobem, který ti brání potkat něco nového.",
    cta: "Chceš vědět, co Smrt znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "umirnenost", name: "Umírněnost", section: "Velká arkána", appId: "mirnost",
    intro: ["Umírněnost přelévá vodu mezi dvěma poháry, jedním nohou na zemi, druhou ve vodě, v naprosté rovnováze mezi dvěma světy. Je to karta harmonie a trpělivého slaďování."],
    up: "*Vzpřímeně* ve vztahu jde o schopnost sladit dvě různá tempa a dvě různé povahy tak, aby z toho vzniklo něco lepšího, než co byste měli zvlášť. Pokud jsi sama, karta ukazuje, že hledáš (nebo bys měla hledat) partnera, se kterým lze najít rovnováhu, ne extrém.",
    rev: "*Obráceně* se objevuje vychýlení na jednu stranu: příliš citu, nebo naopak chladu, příliš dávání, nebo příliš braní. Ve vztahu to bývá nerovnováha, o které oba víte, ale nikdo ji nepojmenoval. V samostatnosti karta varuje před extrémními požadavky na partnera nebo na sebe samu.",
    cta: "Chceš vědět, co Umírněnost znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "dabel", name: "Ďábel", section: "Velká arkána", appId: "dabel",
    intro: ["Ďábel ukazuje pár spoutaný řetězy u trůnu rohaté postavy, ale řetězy jsou volné, dají se sundat kdykoli. Je to karta pout, které si často vytváříme sami."],
    up: "*Vzpřímeně* v lásce jde o silnou přitažlivost, která ale nemusí být zdravá. Ve vztahu to bývá otázka, zda vás k sobě táhne skutečná láska, nebo vzorec, který znáš odjinud a nedělá ti dobře. Pokud jsi sama, karta upozorňuje na tendenci přitahovat typ vztahu, ze kterého se špatně odchází.",
    rev: "*Obráceně* Ďábel ukazuje uvolnění z pouta: rozpoznání toxického vzorce, nebo odchod ze závislosti na tom být potřebná. Ve vztahu jde o návrat kontroly nad vlastním životem po období, kdy jsi ji předala jinému. V samostatnosti karta signalizuje, že první kroky ven ze starého vzorce jsou nejisté, ale správné.",
    cta: "Chceš vědět, co Ďábel znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "vez", name: "Věž", section: "Velká arkána", appId: "vez",
    intro: ["Věž patří mezi karty, kterých se lidé v tarotu bojí nejvíc, a v lásce právem: často se ukáže přesně ve chvíli, kdy něco, o čem jsi dlouho tušila, že není v pořádku, náhle vyjde najevo. Není to karta trestu. Je to karta pravdy, která přichází rychleji, než by sis přála."],
    up: "*Vzpřímeně* v otázkách lásky Věž mluví o odhalení. Něco, co drželo vztah pohromadě jen zdánlivě, se hroutí, ať už jde o důvěru, o iluzi, kterou sis o druhém člověku vytvořila, nebo o rovnováhu, která byla od začátku vratká. Pokud jsi ve vztahu, jde často o skrytou pravdu, která konečně dostane jméno, a rozhovor, kterému jste se oba dlouho vyhýbali. Pokud jsi single, může jít o prohlédnutí vzoru, který tě dosud táhl ke stejnému typu zklamání. Bolí to, protože přichází bez varování. Ale to, co Věž bourá, nikdy nebylo tak pevné, jak se zdálo, a to, co po ní zůstane, se dá stavět znovu, tentokrát na pravdě. Je to úleva, která zatím bolí.",
    rev: "*Obráceně* Věž ukazuje totéž zpomalené, nebo oddalované. Otřes, kterému se snažíš vyhnout, už se ve skutečnosti odehrál, jen sis ho ještě nepřiznala, nebo se blíží a ty před ním zavíráš oči, protože je jednodušší nevidět. Ve vztahu to bývá pravda, o které oba víte, ale žádný z vás ji nevysloví nahlas. V samostatnosti to bývá varovný signál, kterému nevěnuješ pozornost, protože se ti do něj nechce věřit. Obrácená poloha nemusí znamenat, že jsi v bezpečí. Často znamená jen odklad.",
    cta: "Chceš vědět, co Věž znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "hvezda", name: "Hvězda", section: "Velká arkána", appId: "hvezda",
    intro: ["Hvězda klečí u vody a nalévá ji ze dvou džbánů, jeden zpět do potoka, druhý na zem. Je to karta naděje po bouři a tiché obnovy víry."],
    up: "*Vzpřímeně* ve vztahu přichází po náročnějším období nadech úlevy: pocit, že to nejhorší je za vámi a je zase na co se těšit. Pokud jsi sama, karta obnovuje víru, že láska má smysl zkoušet znovu, i po zklamání, které bolelo.",
    rev: "*Obráceně* je naděje vyčerpaná, ne ztracená navždy. Ve vztahu jde o pochybnost, zda má vůbec cenu dál investovat energii. V samostatnosti karta ukazuje únavu z hledání, pocit, že sis přestala věřit, že si lásku zasloužíš nebo že přijde.",
    cta: "Chceš vědět, co Hvězda znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "mesic", name: "Měsíc", section: "Velká arkána", appId: "mesic",
    intro: ["Měsíc svítí nad krajinou plnou stínů, kde nic není úplně jasné a cesta vede rovnou přes neznámé vody. Je to karta intuice, iluzí a věcí, které se teprve mají vyjasnit."],
    up: "*Vzpřímeně* ve vztahu jde o nejasnost, kterou nemusíš hned řešit: něco tě znepokojuje, ale ještě nemáš všechny informace, a stačí důvěřovat pocitu, i když ho zatím neumíš zdůvodnit. Pokud jsi sama, karta varuje před tím, brát věci jen podle prvního dojmu.",
    rev: "*Obráceně* se mlha pomalu rozjasňuje. Ve vztahu jde o konec sebeklamu, pravdu, kterou sis dlouho nechtěla přiznat, ale teď se stává zřejmou. V samostatnosti karta ukazuje, že přestáváš věřit iluzi o někom, kdo nebyl tím, za koho jsi ho měla.",
    cta: "Chceš vědět, co Měsíc znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "slunce", name: "Slunce", section: "Velká arkána", appId: "slunce",
    intro: ["Slunce svítí nad dítětem na bílém koni, bez stínu a bez pochybností. Je to nejjasnější a nejupřímnější karta celého balíčku."],
    up: "*Vzpřímeně* ve vztahu přináší lehkost, radost a upřímnost bez postranních úmyslů. Je to čas říct nahlas, co tě těší, bez obav, že to zakřikneš. Pokud jsi sama, karta signalizuje období, ve kterém jsi šťastná sama se sebou, a to je přesně energie, která přitahuje zdravou lásku.",
    rev: "*Obráceně* je radost zastřená, možná přeháníš optimismus, abys nemusela vidět, co skutečně drhne. Ve vztahu jde o přehlížení problému pod rouškou dobré nálady. V samostatnosti karta varuje před falešným „je mi to jedno\" tam, kde ti ve skutečnosti záleží víc, než přiznáváš.",
    cta: "Chceš vědět, co Slunce znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "soud", name: "Soud", section: "Velká arkána", appId: "soud",
    intro: ["Soud zobrazuje postavy vstávající z hrobů na zvuk anděla trubícího na trubku, probuzení a zúčtování s minulostí. Je to karta, která volá k vědomí to, co jsi dlouho věděla, ale neřešila."],
    up: "*Vzpřímeně* ve vztahu jde o návrat něčeho z minulosti k rozhodnutí, staré téma, které se konečně vyřeší, nebo poučení z předchozího vztahu, které si teď bereš vědomě s sebou. Pokud jsi sama, karta ukazuje probuzení k tomu, co v lásce doopravdy chceš, ne co sis dosud jen myslela, že bys měla chtít.",
    rev: "*Obráceně* soudíš sebe (nebo druhého) tvrději, než je fér. Ve vztahu jde o neschopnost odpustit staré chyby, svoje i partnerovy. V samostatnosti karta zve k smíření s minulým rozhodnutím, ať jsi zůstala, nebo odešla.",
    cta: "Chceš vědět, co Soud znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "svet", name: "Svět", section: "Velká arkána", appId: "svet",
    intro: ["Svět ukazuje tančící postavu obklopenou vavřínovým věncem, symbolem dokončení a celistvosti. Je to poslední karta velké arkány, uzavření kruhu."],
    up: "*Vzpřímeně* ve vztahu jde o pocit naplnění: fáze, kterou jste spolu prošli, dává smysl a stojí na pevných základech. Pokud jsi sama, karta signalizuje uzavření období hledání, pocit, že sis touhle cestou zasloužila naučit něco důležitého o lásce a o sobě.",
    rev: "*Obráceně* zůstává něco nedokončené: rozhovor, který se pořád odkládá, kapitola, která se táhne déle, než by měla. Ve vztahu jde o pocit topení se na místě, kde chybí poslední krok k uzavření tématu. V samostatnosti karta ukazuje nedokončenou práci na sobě, kterou je potřeba dodělat, než bude prostor pro něco nového.",
    cta: "Chceš vědět, co Svět znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "eso-holi", name: "Eso holí", section: "Malá arkána: Hole", appId: "eso-hole",
    intro: ["Eso holí je čistá jiskra, ruka vystupující z oblaku a svírající pučící hůl. V lásce znamená chvíli, kdy se něco vznítí, ať jde o nové setkání, nebo o návrat chuti do vztahu, který začínal ochládat."],
    up: "*Vzpřímeně* ve vztahu jde o návrat chemie a touhy, chuť dělat věci spolu s nadšením, ne z povinnosti. Pokud jsi sama, karta signalizuje silnou přitažlivost na obzoru, setkání, po kterém ucítíš jiskru, kterou jsi dlouho nezažila.",
    rev: "*Obráceně* jiskra zatím nechce vzplanout. Ve vztahu jde o pocit, že vášeň vyprchala nebo že se pokus o oživení nedaří. V samostatnosti karta ukazuje falešný start, přitažlivost, která rychle vyprchá dřív, než se z ní stane cokoli skutečného.",
    cta: "Chceš vědět, co Eso holí znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "dvojka-holi", name: "Dvojka holí", section: "Malá arkána: Hole", appId: "dvojka-hole",
    intro: ["Postava stojí na hradbách a drží glóbus, hledí do dálky s hůlkou v ruce. Karta rozhodování, kam dál a s kým."],
    up: "*Vzpřímeně* ve vztahu jde o plánování společné budoucnosti, rozhodnutí, které vás oba posune dál, ať jde o stěhování, nebo o hlubší závazek. Pokud jsi sama, karta ukazuje, že máš teď na výběr směr, kterým se v lásce vydáš, a stojí za to se rozhodnout vědomě.",
    rev: "*Obráceně* se rozhodování zadrhává. Ve vztahu jde o strach z dalšího kroku, o odkládání rozhovoru o budoucnosti, protože je pohodlnější zůstat, kde jste. V samostatnosti karta ukazuje nerozhodnost, která tě drží na místě déle, než by bylo zdrávo.",
    cta: "Chceš vědět, co Dvojka holí znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "trojka-holi", name: "Trojka holí", section: "Malá arkána: Hole", appId: "trojka-hole",
    intro: ["Postava stojí na útesu a sleduje lodě mířící k obzoru, s důvěrou, že se vrátí naložené. Karta očekávání, které má základ v tom, co jsi už zasela."],
    up: "*Vzpřímeně* ve vztahu jde o období, kdy se začíná ukazovat, kam váš vztah roste, plány dostávají tvar a začínáte hledět společně dopředu. Pokud jsi sama, karta naznačuje, že to, co jsi do seznamování vložila, se brzy vrátí, jen to potřebuje čas doplout.",
    rev: "*Obráceně* lodě váznou na obzoru. Ve vztahu jde o zklamání z toho, že se očekávaný posun nekoná, plány se táhnou beze změny. V samostatnosti karta ukazuje netrpělivost s tempem, jakým se věci hýbou, nebo pocit, že čekáš na něco, co nepřichází.",
    cta: "Chceš vědět, co Trojka holí znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "ctyrka-holi", name: "Čtyřka holí", section: "Malá arkána: Hole", appId: "ctyrka-hole",
    intro: ["Čtyři hole tvoří slavnostní bránu ozdobenou květinami, za kterou lidé oslavují. Je to karta domova, oslavy a milníku, na který jste si zasloužili se těšit."],
    up: "*Vzpřímeně* ve vztahu jde o radostnou událost, zásnuby, nastěhování, výročí, chvíli, kdy stojí za to zastavit se a připomenout si, jak daleko jste došli. Pokud jsi sama, karta ukazuje pocit domova, který si budeš schopná vytvořit s někým, kdo přijde, protože ho už nosíš v sobě.",
    rev: "*Obráceně* se oslava odkládá. Ve vztahu jde o nestabilitu v domácím zázemí, milník, který se odsouvá, nebo napětí kolem toho, co by měla „správná\" oslava obnášet. V samostatnosti karta ukazuje pocit, že ti domov ještě chybí, i kdyby šlo jen o pocit doma sama v sobě.",
    cta: "Chceš vědět, co Čtyřka holí znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "petka-holi", name: "Pětka holí", section: "Malá arkána: Hole", appId: "petka-hole",
    intro: ["Pět postav se přetahuje s holemi v rukou, zdánlivě v chaosu, který ale nikomu neubližuje doopravdy. Karta drobných sporů a soutěžení."],
    up: "*Vzpřímeně* ve vztahu jde o hádky kvůli maličkostem, soutěžení o to, kdo má pravdu, spíš než o skutečný konflikt. Pokud jsi sama, karta ukazuje období, kdy narážíš na víc konkurence nebo komplikací v seznamování, než by sis přála.",
    rev: "*Obráceně* se otevřený spor mění v tiché napětí. Ve vztahu jde o vyhýbání se hádce, která by nakonec pomohla víc, než škodí, protože nevyřčené neshody hnijí pod povrchem. V samostatnosti karta ukazuje únavu z neustálého poměřování se s ostatními.",
    cta: "Chceš vědět, co Pětka holí znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "sestka-holi", name: "Šestka holí", section: "Malá arkána: Hole", appId: "sestka-hole",
    intro: ["Jezdec na koni se vrací vítězně, vavřínový věnec na hlavě, dav ho vítá. Karta uznání a zasloužené výhry."],
    up: "*Vzpřímeně* ve vztahu jde o pocit, že vaše spojení konečně dostává uznání, ať už od okolí, nebo jen od vás samotných po náročném období. Pokud jsi sama, karta ukazuje sebevědomí, díky kterému přitahuješ pozornost přesně těch lidí, o které stojíš.",
    rev: "*Obráceně* uznání chybí, nebo je předčasné slavit. Ve vztahu jde o pocit, že vaše spojení zůstává skryté nebo nedoceněné, veřejně nebo mezi vámi navzájem. V samostatnosti karta varuje před přehnaným sebevědomím, které maskuje nejistotu.",
    cta: "Chceš vědět, co Šestka holí znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "sedmicka-holi", name: "Sedmička holí", section: "Malá arkána: Hole", appId: "sedmicka-hole",
    intro: ["Postava stojí na vyvýšeném místě a brání se šesti holím zdola. Karta obhajoby toho, na čem ti záleží."],
    up: "*Vzpřímeně* ve vztahu jde o hájení svého postoje, i pod tlakem okolí nebo pochybností, protože víš, co pro vás dva funguje. Pokud jsi sama, karta ukazuje potřebu stát si za svými hranicemi v seznamování, i když to znamená odmítnout někoho netrpělivého.",
    rev: "*Obráceně* dochází síla se dál bránit. Ve vztahu jde o pocit, že už nemáš energii obhajovat vztah proti kritice zvenčí nebo proti vlastním pochybnostem. V samostatnosti karta ukazuje vzdávání se svých hranic jen proto, aby byl klid.",
    cta: "Chceš vědět, co Sedmička holí znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "osmicka-holi", name: "Osmička holí", section: "Malá arkána: Hole", appId: "osmicka-hole",
    intro: ["Osm holí letí vzduchem směrem k zemi, rychle a bez zastávky. Karta zrychleného pohybu a zpráv, které přicházejí rychle za sebou."],
    up: "*Vzpřímeně* ve vztahu jde o zrychlení, věci se hýbou rychle, zprávy létají, rozhodnutí padají rychleji, než jsi čekala. Pokud jsi sama, karta ukazuje rychlý vývoj v seznamování, zprávy a pozornost přicházející v rychlém sledu.",
    rev: "*Obráceně* se rychlost zadrhává. Ve vztahu jde o zpoždění, komunikaci, která najednou vázne, ticho tam, kde bylo tempo. V samostatnosti karta ukazuje frustraci z toho, že se něco slibně rozjeté náhle zpomalilo nebo zaseklo.",
    cta: "Chceš vědět, co Osmička holí znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "devitka-holi", name: "Devítka holí", section: "Malá arkána: Hole", appId: "devitka-hole",
    intro: ["Zraněná, ale ostražitá postava stojí na stráži s holí v ruce, připravená bránit se dál. Karta odolnosti po předchozích ranách."],
    up: "*Vzpřímeně* ve vztahu jde o obezřetnost, kterou sis vypěstovala po dřívějším zklamání, a schopnost i přes ni zůstat ve vztahu otevřená. Pokud jsi sama, karta ukazuje ostražitost vůči novému seznámení, protože minulost tě naučila být opatrná.",
    rev: "*Obráceně* se ostražitost mění v zeď, kterou nikdo neprojde. Ve vztahu jde o neustálé čekání na to, kdy přijde další rána, i když k tomu není důvod. V samostatnosti karta ukazuje vyčerpání ze stálé obrany, které brání i dobrému vztahu přiblížit se.",
    cta: "Chceš vědět, co Devítka holí znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "desitka-holi", name: "Desítka holí", section: "Malá arkána: Hole", appId: "desitka-hole",
    intro: ["Postava se sotva vleče pod tíhou deseti holí, které nese sama, i když cíl je už na dohled. Karta břemene, které jsi na sebe vzala víc, než bylo nutné."],
    up: "*Vzpřímeně* ve vztahu jde o pocit, že neseš většinu odpovědnosti sama, emočně i prakticky, a únava z toho začíná být znát. Pokud jsi sama, karta ukazuje, že si na sebe bereš víc starostí o budoucí vztah, než je zdravé, ještě než vůbec začal.",
    rev: "*Obráceně* karta zve k odložení břemene. Ve vztahu jde o chvíli, kdy je potřeba přenechat část zodpovědnosti druhému, místo abys nesla všechno sama. V samostatnosti karta ukazuje úlevu z toho, že přestáváš řešit věci, které nejsou tvoje na starost.",
    cta: "Chceš vědět, co Desítka holí znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "paze-holi", name: "Páže holí", section: "Malá arkána: Hole", appId: "paze-hole",
    intro: ["Mladá postava s holí v ruce hledí do dálky s nadšením někoho, kdo právě objevil něco vzrušujícího. Karta hravé zprávy nebo nového zájmu."],
    up: "*Vzpřímeně* ve vztahu jde o návrat hravosti a spontánních zpráv, chuti překvapit se navzájem. Pokud jsi sama, karta signalizuje flirtovací energii, možná zprávu nebo pozornost od někoho, kdo tě upřímně zaujal.",
    rev: "*Obráceně* je nadšení jen na povrchu. Ve vztahu jde o nevyzrálou komunikaci, sliby bez činů. V samostatnosti karta varuje před někým, kdo umí skvěle flirtovat, ale za slovy nic nenásleduje.",
    cta: "Chceš vědět, co Páže holí znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "rytir-holi", name: "Rytíř holí", section: "Malá arkána: Hole", appId: "rytir-hole",
    intro: ["Rytíř vyráží v plné zbroji na koni, který se vzpíná, netrpělivý vyrazit vpřed. Karta vášnivého pronásledování a rychlého tempa."],
    up: "*Vzpřímeně* ve vztahu jde o vlnu vášně a dobrodružství, chuť dělat impulzivní gesta z lásky. Pokud jsi sama, karta ukazuje vířivou známost, někoho, kdo přichází s intenzitou a rychlým tempem, které tě strhne.",
    rev: "*Obráceně* vášeň hoří příliš rychle a stejně rychle zhasíná. Ve vztahu jde o unáhlenost, slibovaná dobrodružství, která se nikdy nekonají. V samostatnosti karta varuje před typem, který vzplane a zmizí dřív, než stihneš zjistit, o co šlo doopravdy.",
    cta: "Chceš vědět, co Rytíř holí znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "kralovna-holi", name: "Královna holí", section: "Malá arkána: Hole", appId: "kralovna-hole",
    intro: ["Královna sedí na trůnu se slunečnicí v ruce, sebejistá, vřelá a přitažlivá bez nutnosti o to usilovat. Karta magnetismu, který vychází z klidné jistoty v sobě samé."],
    up: "*Vzpřímeně* ve vztahu jde o sebevědomí, které vztahu prospívá, protože nepotřebuješ partnera k tomu, abys byla celistvá, jen ho chceš mít vedle sebe. Pokud jsi sama, karta ukazuje, že tvá vlastní jistota je teď to, co přitahuje pozornost víc než cokoli jiného.",
    rev: "*Obráceně* se jistota mění v potřebu neustálého potvrzení. Ve vztahu jde o žárlivost nebo nárokovost, strach ze ztráty pozornosti. V samostatnosti karta ukazuje potlačené sebevědomí, schované za předstíranou lhostejností.",
    cta: "Chceš vědět, co Královna holí znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "kral-holi", name: "Král holí", section: "Malá arkána: Hole", appId: "kral-hole",
    intro: ["Král sedí na trůnu se salamandry, symboly ohně, který neuhasíná. Karta vizionářské, charismatické energie, která vede, ale nepotřebuje nikoho ovládat."],
    up: "*Vzpřímeně* ve vztahu jde o partnera (nebo tebe samotnou), který inspiruje k větším cílům a přitom respektuje nezávislost druhé strany. Pokud jsi sama, karta ukazuje přitažlivost k někomu charismatickému a jistému si sám sebou, kdo vede vlastním příkladem.",
    rev: "*Obráceně* se charisma mění v ovládání. Ve vztahu jde o ego, které chce mít navrch, nebo netrpělivost s tempem druhého. V samostatnosti karta varuje před typem, který okouzlí, ale ve skutečnosti potřebuje být vždy středem pozornosti.",
    cta: "Chceš vědět, co Král holí znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "eso-poharu", name: "Eso pohárů", section: "Malá arkána: Poháry", appId: "eso-pohary",
    intro: ["Ruka vystupující z oblaku drží pohár, ze kterého přetéká voda, a holubice se snáší k jeho okraji. Je to karta čistého citu, chvíle, kdy srdce poprvé nebo znovu přeteče láskou."],
    up: "*Vzpřímeně* ve vztahu jde o novou vlnu emoční blízkosti, otevření srdce, které bylo dosud opatrné. Pokud jsi sama, karta signalizuje začátek citového pouta, které přichází s hloubkou, jakou jsi dlouho nezažila.",
    rev: "*Obráceně* zůstává pohár nakloněný, ale prázdný. Ve vztahu jde o citové odpojení, blízkost, která se necítí tak plná jako dřív. V samostatnosti karta ukazuje potlačované city nebo strach otevřít srdce po předchozím zklamání.",
    cta: "Chceš vědět, co Eso pohárů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "dvojka-poharu", name: "Dvojka pohárů", section: "Malá arkána: Poháry", appId: "dvojka-pohary",
    intro: ["Dvě postavy si vyměňují poháry tváří v tvář, nad nimi se vznáší okřídlený lví symbol spojující jejich energie. Karta vzájemnosti a rovnocenného spojení."],
    up: "*Vzpřímeně* ve vztahu jde o harmonii a vzájemné porozumění, chvíli, kdy oba dáváte a přijímáte ve stejné míře. Pokud jsi sama, karta ukazuje setkání, ve kterém se od první chvíle cítíte jako rovnocenní partneři, ne jako lovec a kořist.",
    rev: "*Obráceně* se rovnováha naklání na jednu stranu. Ve vztahu jde o nesoulad, jeden dává víc než druhý, nebo se komunikace láme. V samostatnosti karta varuje před spojením, které vypadá slibně, ale chybí mu vzájemnost.",
    cta: "Chceš vědět, co Dvojka pohárů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "trojka-poharu", name: "Trojka pohárů", section: "Malá arkána: Poháry", appId: "trojka-pohary",
    intro: ["Tři ženy zvedají poháry k přípitku, tančí spolu v radosti ze sdíleného okamžiku. Karta oslavy, přátelství a podpory kolem lásky."],
    up: "*Vzpřímeně* ve vztahu jde o radost sdílenou nejen mezi vámi dvěma, ale i s okolím, přátelé a rodina váš vztah podporují a slaví s vámi. Pokud jsi sama, karta ukazuje, že síla přátelství tě teď nese víc než osamělé čekání na partnera.",
    rev: "*Obráceně* se oslava mění v přebytek. Ve vztahu jde o třetí osobu narušující vaše spojení, drby nebo přehnané zapojování okolí do vašich záležitostí. V samostatnosti karta varuje před hledáním útěchy v nadměrném rozptýlení místo skutečného řešení citů.",
    cta: "Chceš vědět, co Trojka pohárů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "ctyrka-poharu", name: "Čtyřka pohárů", section: "Malá arkána: Poháry", appId: "ctyrka-pohary",
    intro: ["Postava sedí pod stromem se založenýma rukama, lhostejně přehlíží nabízený pohár, který se jí vznáší před obličejem. Karta citové otupělosti a přehlížení toho, co je nabízeno."],
    up: "*Vzpřímeně* ve vztahu jde o pocit stagnace, nudy nebo lhostejnosti, kdy přestáváš vnímat dobré věci, které vztah nabízí. Pokud jsi sama, karta upozorňuje, že možná přehlížíš zajímavou nabídku nebo zájem, protože jsi zabraná do vlastní nespokojenosti.",
    rev: "*Obráceně* se otupělost probouzí. Ve vztahu jde o nový zájem, ochotu zkusit něco, co jsi dřív odmítala. V samostatnosti karta ukazuje otevření se novým možnostem po období lhostejnosti k seznamování.",
    cta: "Chceš vědět, co Čtyřka pohárů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "petka-poharu", name: "Pětka pohárů", section: "Malá arkána: Poháry", appId: "petka-pohary",
    intro: ["Postava v černém plášti hledí na tři rozlité poháry, zatímco za jejími zády stojí dva plné, kterých si nevšímá. Karta zármutku, který zastiňuje to, co ještě zbývá."],
    up: "*Vzpřímeně* ve vztahu jde o smutek ze ztráty nebo zklamání, které tě natolik pohlcuje, že nevidíš, co ve vztahu ještě funguje. Pokud jsi sama, karta ukazuje zármutek nad minulým vztahem, který ti brání vidět, že se před tebou otevírají nové možnosti.",
    rev: "*Obráceně* se pohled obrací od rozlitého k tomu, co zbylo. Ve vztahu jde o začátek odpuštění, uzavírání staré bolesti. V samostatnosti karta signalizuje, že se konečně dokážeš dívat dopředu, ne jen na to, co jsi ztratila.",
    cta: "Chceš vědět, co Pětka pohárů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "sestka-poharu", name: "Šestka pohárů", section: "Malá arkána: Poháry", appId: "sestka-pohary",
    intro: ["Dvě děti si vyměňují poháry plné květin na zahradě starého domu. Karta nostalgie, dětské nevinnosti a vzpomínek na minulou lásku."],
    up: "*Vzpřímeně* ve vztahu jde o návrat něhy a bezpečí, jaké jste cítili na začátku, nebo o vztah, který se vrací ke svým kořenům. Pokud jsi sama, karta ukazuje starou známost nebo lásku z minulosti, která se může vrátit, případně vzpomínku, která ti pomáhá pochopit, co v lásce doopravdy chceš.",
    rev: "*Obráceně* uvízne nostalgie v minulosti. Ve vztahu jde o srovnávání současnosti s idealizovanou minulostí, které brání žít přítomnost. V samostatnosti karta varuje před lpěním na vztahu, který už dávno skončil.",
    cta: "Chceš vědět, co Šestka pohárů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "sedmicka-poharu", name: "Sedmička pohárů", section: "Malá arkána: Poháry", appId: "sedmicka-pohary",
    intro: ["Postava hledí na sedm pohárů plných fantazie, klamu i skutečných možností, vznášejících se v oblacích, a neví, který si vybrat. Karta příliš mnoha možností a nutnosti rozlišit iluzi od reality."],
    up: "*Vzpřímeně* ve vztahu jde o zmatek z protichůdných přání nebo z toho, co si o vztahu namlouváš, oproti tomu, co je skutečné. Pokud jsi sama, karta upozorňuje na příliš mnoho možností k výběru bez jasného kritéria, které z nich mají skutečnou hodnotu.",
    rev: "*Obráceně* se mlha rozptyluje. Ve vztahu jde o jasnější vidění toho, co doopravdy chceš, po období zmatku. V samostatnosti karta ukazuje konečné rozlišení mezi tím, kdo ti dělá dobře, a kdo je jen líbivá iluze.",
    cta: "Chceš vědět, co Sedmička pohárů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "osmicka-poharu", name: "Osmička pohárů", section: "Malá arkána: Poháry", appId: "osmicka-pohary",
    intro: ["Postava se zády k osmi naskládaným pohárům odchází do hor, pryč od toho, co postavila, hledat něco hlubšího. Karta odchodu, který není útěkem, ale hledáním smyslu."],
    up: "*Vzpřímeně* ve vztahu jde o pocit, že něco, co jste spolu budovali, už nestačí, a je čas hledat hlouběji, ať v samotném vztahu, nebo mimo něj. Pokud jsi sama, karta ukazuje odvahu odejít od pohodlného, ale neuspokojivého seznamování k něčemu, co má skutečný smysl.",
    rev: "*Obráceně* zůstáváš stát, i když víš, že bys měla jít dál. Ve vztahu jde o strach opustit něco, co už nefunguje, jen ze strachu z neznáma. V samostatnosti karta varuje před uvíznutím ve vzoru, o kterém víš, že tě nenaplňuje.",
    cta: "Chceš vědět, co Osmička pohárů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "devitka-poharu", name: "Devítka pohárů", section: "Malá arkána: Poháry", appId: "devitka-pohary",
    intro: ["Spokojená postava sedí se založenýma rukama před řadou devíti pohárů, jako trofejemi vlastní spokojenosti. Karta naplnění a vděčnosti za to, co máš."],
    up: "*Vzpřímeně* ve vztahu jde o pocit citového naplnění, spokojenost, která nepotřebuje nic dokazovat okolí. Pokud jsi sama, karta ukazuje spokojenost sama se sebou, ze které přirozeně vyzařuje přitažlivost bez zoufalého hledání.",
    rev: "*Obráceně* je spokojenost jen předstíraná. Ve vztahu jde o povrchní štěstí, které schovává nevyřčenou nespokojenost. V samostatnosti karta varuje před sebeuspokojením, které brání otevřít se skutečné blízkosti.",
    cta: "Chceš vědět, co Devítka pohárů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "desitka-poharu", name: "Desítka pohárů", section: "Malá arkána: Poháry", appId: "desitka-pohary",
    intro: ["Rodina stojí s rozpaženýma rukama pod duhou s deseti poháry, děti tančí opodál. Karta citového naplnění a harmonie, o jaké sníme jako o domovu."],
    up: "*Vzpřímeně* ve vztahu jde o hluboké, trvalé štěstí, pocit, že jste doma jeden u druhého. Pokud jsi sama, karta ukazuje, že se blížíš k typu vztahu, který přináší přesně tenhle druh naplnění, rodinný, trvalý a bezpečný.",
    rev: "*Obráceně* je harmonie jen na povrchu. Ve vztahu jde o rozpor mezi tím, jak vztah vypadá zvenčí, a jak se ve skutečnosti cítí zevnitř. V samostatnosti karta ukazuje idealizovanou představu o rodinném štěstí, která tě může vést ke špatným kompromisům.",
    cta: "Chceš vědět, co Desítka pohárů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "paze-poharu", name: "Páže pohárů", section: "Malá arkána: Poháry", appId: "paze-pohary",
    intro: ["Mladá postava hledí užasle na rybu vykukující z poháru, otevřená neočekávanému a citlivá na city, co teprve klíčí. Karta citové zprávy nebo něžného, nesmělého zájmu."],
    up: "*Vzpřímeně* ve vztahu jde o návrat citlivosti a upřímných gest, chuti dělat si navzájem radost drobnostmi. Pokud jsi sama, karta signalizuje jemný, upřímný zájem od někoho citlivého, možná i zprávu, která tě mile překvapí.",
    rev: "*Obráceně* je citlivost jen přetvářka. Ve vztahu jde o citové hry nebo nezralost v tom, jak druhý vyjadřuje své pocity. V samostatnosti karta varuje před tím, brát přehnaně romantická gesta za skutečnou hloubku citu.",
    cta: "Chceš vědět, co Páže pohárů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "rytir-poharu", name: "Rytíř pohárů", section: "Malá arkána: Poháry", appId: "rytir-pohary",
    intro: ["Rytíř jede klidným tempem s pohárem nabízeným před sebou jako pozvání, ne jako útok. Karta romantického gesta a citového sblížení nabízeného s upřímností."],
    up: "*Vzpřímeně* ve vztahu jde o romantiku, něžná gesta a citovou otevřenost, chvíli, kdy se cítíš skutečně sblížená. Pokud jsi sama, karta ukazuje příchod někoho romantického, citlivého, kdo se ti dvoří s upřímným zájmem, ne jen s vypočítavostí.",
    rev: "*Obráceně* je romantické gesto jen prázdná forma. Ve vztahu jde o citové rozladění, sliby lásky, které nejsou podložené skutky. V samostatnosti karta varuje před typem, který umí krásně mluvit o citech, ale za slovy zůstává prázdno.",
    cta: "Chceš vědět, co Rytíř pohárů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "kralovna-poharu", name: "Královna pohárů", section: "Malá arkána: Poháry", appId: "kralovna-pohary",
    intro: ["Královna sedí u moře a hledí do zdobeného poháru jako do zrcadla vlastní duše, citlivá, ale ne přehlcená. Karta emoční moudrosti a hluboké empatie."],
    up: "*Vzpřímeně* ve vztahu jde o citovou zralost, schopnost naslouchat druhému i sobě bez soudu. Pokud jsi sama, karta ukazuje, že tvá citová hloubka a empatie jsou teď tím, co přitahuje lidi, kteří hledají skutečné porozumění, ne jen povrchní známost.",
    rev: "*Obráceně* se citlivost mění v přecitlivělost nebo utápění se v náladách druhých. Ve vztahu jde o ztrátu vlastních hranic uprostřed emocí partnera. V samostatnosti karta varuje před přílišnou empatií vůči lidem, kteří ji nevrací.",
    cta: "Chceš vědět, co Královna pohárů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "kral-poharu", name: "Král pohárů", section: "Malá arkána: Poháry", appId: "kral-pohary",
    intro: ["Král sedí na trůnu uprostřed rozbouřeného moře, klidný a vyrovnaný navzdory vlnám kolem sebe. Karta emoční vyrovnanosti a schopnosti zvládat city, aniž by ses jimi nechala strhnout."],
    up: "*Vzpřímeně* ve vztahu jde o partnera (nebo tebe samotnou), který zvládá city s klidem a laskavostí, i uprostřed konfliktu. Pokud jsi sama, karta ukazuje přitažlivost k někomu citově vyzrálému, komu se dá věřit i v bouřlivých chvílích.",
    rev: "*Obráceně* se klid mění v potlačování citů. Ve vztahu jde o citový chlad nebo pasivní agresi místo otevřeného vyjádření pocitů. V samostatnosti karta varuje před typem, který navenek působí vyrovnaně, ale své emoce nikdy skutečně neukáže.",
    cta: "Chceš vědět, co Král pohárů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "eso-mecu", name: "Eso mečů", section: "Malá arkána: Meče", appId: "eso-mece",
    intro: ["Ruka z oblaku svírá meč korunovaný vavřínem, jasný a ostrý jako první opravdu pravdivá myšlenka po dlouhém zmatku. Karta jasnozřivosti a rozhodnutí, které konečně vidíš černé na bílém."],
    up: "*Vzpřímeně* ve vztahu jde o chvíli, kdy se konečně vyjasní, co si oba doopravdy myslíte, a ta jasnost, i kdyby bolela, uleví víc než další mlžení. Pokud jsi sama, karta ukazuje moment, kdy přesně víš, co v lásce chceš, a přestáváš si to zdůvodňovat.",
    rev: "*Obráceně* zůstává jasnost zakalená. Ve vztahu jde o zmatenou komunikaci, kdy si nejste jistí, co ten druhý vlastně řekl nebo myslel. V samostatnosti karta ukazuje rozhodnutí založené na neúplných nebo zkreslených informacích.",
    cta: "Chceš vědět, co Eso mečů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "dvojka-mecu", name: "Dvojka mečů", section: "Malá arkána: Meče", appId: "dvojka-mece",
    intro: ["Postava se zavázanýma očima sedí se zkříženými meči na hrudi, zády k moři, které nevidí. Karta rozhodnutí, kterému se vyhýbáš tím, že si zavážeš oči."],
    up: "*Vzpřímeně* ve vztahu jde o patovou situaci, kdy oba víte, že je potřeba něco rozhodnout, a přesto to nikdo neudělá. Pokud jsi sama, karta ukazuje nerozhodnost mezi dvěma možnostmi v lásce, kterou řešíš tím, že o ní prostě nemluvíš.",
    rev: "*Obráceně* se slepota buď prolomí, nebo prohloubí. Ve vztahu jde buď o konečné odkrytí toho, co bylo dlouho ignorováno, nebo o zahlcení tolika informacemi najednou, že je těžké se v nich zorientovat. V samostatnosti karta ukazuje rozhodnutí, které na tebe čeká, ať se mu chceš vyhnout, jak chceš.",
    cta: "Chceš vědět, co Dvojka mečů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "trojka-mecu", name: "Trojka mečů", section: "Malá arkána: Meče", appId: "trojka-mece",
    intro: ["Tři meče probodávají srdce na pozadí bouřkových mraků. Je to karta, kterou se lidé bojí vytáhnout, protože přesně pojmenovává bolest zlomeného srdce."],
    up: "*Vzpřímeně* ve vztahu jde o bolestivou pravdu, zradu nebo zklamání, které je potřeba prožít, ne obejít. Pokud jsi sama, karta ukazuje čerstvý nebo starý zármutek ze ztráty, který si zaslouží prostor, ne rychlé přeskočení. Bolest, kterou karta ukazuje, je skutečná, ale není konečná.",
    rev: "*Obráceně* se bolest začíná hojit. Ve vztahu jde o odpuštění nebo o přijetí toho, co se stalo, aby mohla přijít úleva. V samostatnosti karta ukazuje počátek uzdravení po zlomeném srdci, pomalý, ale skutečný.",
    cta: "Chceš vědět, co Trojka mečů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "ctyrka-mecu", name: "Čtyřka mečů", section: "Malá arkána: Meče", appId: "ctyrka-mece",
    intro: ["Postava leží v tichu chrámu, meče zavěšené nad ní, v klidu, ne v porážce. Karta odpočinku, který si dovolíš po vyčerpávajícím období."],
    up: "*Vzpřímeně* ve vztahu jde o potřebu pauzy od konfliktu, chvíle klidu předtím, než se vrátíte k řešení otázek, které vás vyčerpávají. Pokud jsi sama, karta ukazuje, že si teď zasloužíš odpočinout od hledání, ne se do něj hned zase vrhat.",
    rev: "*Obráceně* se odpočinek nekoná. Ve vztahu jde o nucený návrat do konfliktu dřív, než jsi stihla načerpat síly. V samostatnosti karta ukazuje neklid, který ti nedovolí si odpočinout, i když si to potřebuješ.",
    cta: "Chceš vědět, co Čtyřka mečů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "petka-mecu", name: "Pětka mečů", section: "Malá arkána: Meče", appId: "petka-mece",
    intro: ["Postava sbírá tři meče s vítězným výrazem, zatímco dvě poražené postavy odcházejí se svěšenými hlavami. Karta výhry, která nestojí za cenu, kterou za ni platíš."],
    up: "*Vzpřímeně* ve vztahu jde o hádku, ve které možná „vyhraješ\", ale za cenu důvěry nebo blízkosti, kterou tím ztratíš. Pokud jsi sama, karta varuje před vztahy, kde jde spíš o poměřování sil než o skutečnou blízkost.",
    rev: "*Obráceně* se ozývá touha po smíru. Ve vztahu jde o ochotu pustit staré křivdy a přestat počítat, kdo měl naposledy pravdu. V samostatnosti karta ukazuje uvolnění zraněné pýchy, která ti dosud bránila jít dál.",
    cta: "Chceš vědět, co Pětka mečů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "sestka-mecu", name: "Šestka mečů", section: "Malá arkána: Meče", appId: "sestka-mece",
    intro: ["Postavy se plaví lodí k tišším vodám, meče zabodnuté v přídi, minulost za zády, klidnější obzor před nimi. Karta přechodu od bouřky k tišině."],
    up: "*Vzpřímeně* ve vztahu jde o postupné zklidnění po náročném období, přesun od konfliktu k porozumění. Pokud jsi sama, karta ukazuje cestu pryč od bolestivé minulosti směrem ke klidnějším vodám, i když cesta ještě není u konce.",
    rev: "*Obráceně* zůstáváte na rozbouřené hladině. Ve vztahu jde o odpor k tomu nechat minulost za sebou, opakované vracení se ke starým sporům. V samostatnosti karta ukazuje nedořešenou minulost, která ti brání plout dál.",
    cta: "Chceš vědět, co Šestka mečů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "sedmicka-mecu", name: "Sedmička mečů", section: "Malá arkána: Meče", appId: "sedmicka-mece",
    intro: ["Postava se plíží pryč s pěti meči v náručí a ohlíží se přes rameno, jestli ji někdo nevidí. Karta tajnůstkářství a věcí, které nejsou úplně upřímné."],
    up: "*Vzpřímeně* ve vztahu jde o pocit, že ti něco druhý zatajuje, nebo že sama nejsi tak upřímná, jak by sis přála. Pokud jsi sama, karta radí ověřovat si informace o někom novém, než uvěříš všemu, co ti řekne.",
    rev: "*Obráceně* vychází pravda najevo. Ve vztahu jde o odhalení tajemství nebo o vlastní přiznání toho, co jsi zatajovala. V samostatnosti karta ukazuje konec sebeklamu o někom, kdo nebyl k tobě upřímný.",
    cta: "Chceš vědět, co Sedmička mečů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "osmicka-mecu", name: "Osmička mečů", section: "Malá arkána: Meče", appId: "osmicka-mece",
    intro: ["Postava stojí spoutaná a se zavázanýma očima obklopená meči, ale meče kolem ní tvoří jen řídký kruh, kterým by mohla snadno projít. Karta pocitu bezmoci, který je z velké části vlastní hlavou vytvořený."],
    up: "*Vzpřímeně* ve vztahu jde o pocit uvěznění v situaci, ze které ve skutečnosti existuje cesta ven, jen ji zatím nevidíš. Pokud jsi sama, karta ukazuje přesvědčení, že nemáš na výběr v lásce, i když možnosti existují, jen se bojíš je vidět.",
    rev: "*Obráceně* se pouta uvolňují. Ve vztahu jde o návrat pocitu vlastní moci nad situací, kterou jsi dlouho vnímala jako beznadějnou. V samostatnosti karta ukazuje uvědomění, že past byla z velké části v tvé vlastní hlavě, a že se z ní dá vyjít.",
    cta: "Chceš vědět, co Osmička mečů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "devitka-mecu", name: "Devítka mečů", section: "Malá arkána: Meče", appId: "devitka-mece",
    intro: ["Postava sedí na posteli uprostřed noci, tvář v dlaních, kolem ní devět mečů visících ve tmě. Karta úzkostných myšlenek, které jsou v noci vždycky hlasitější, než jaká je realita ve dne."],
    up: "*Vzpřímeně* ve vztahu jde o starosti a nejhorší scénáře, které si v hlavě přehráváš, často větší, než odpovídá skutečné situaci. Pokud jsi sama, karta ukazuje úzkost z toho, jestli láska vůbec přijde, úzkost, která se ve dne obvykle zmenší. Stojí za to si tyhle myšlenky přebrat s někým, komu věříš, místo abys je nosila v hlavě sama.",
    rev: "*Obráceně* se úzkost buď uvolňuje, nebo konečně vychází najevo. Ve vztahu jde o úlevu, že se obavy nenaplnily tak, jak sis je malovala, nebo naopak o starost, kterou jsi dlouho tajila a je čas ji vyslovit nahlas. V samostatnosti karta ukazuje, že nejhorší noc bývá vždycky před ránem.",
    cta: "Chceš vědět, co Devítka mečů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "desitka-mecu", name: "Desítka mečů", section: "Malá arkána: Meče", appId: "desitka-mece",
    intro: ["Postava leží tváří k zemi s deseti meči v zádech, zatímco na obzoru už vychází slunce. Karta bolestivého konce, po kterém už není kam padat, jen vstát."],
    up: "*Vzpřímeně* ve vztahu jde o definitivní konec kapitoly, možná i samotného vztahu, bolestivý, ale úplný, ne nekonečně natahovaný. Pokud jsi sama, karta ukazuje, že jsi prošla tím nejtěžším, co tahle situace mohla přinést, a odsud vede cesta jen nahoru.",
    rev: "*Obráceně* se zotavení teprve rozjíždí. Ve vztahu jde o pomalé uzdravování po zásadní ráně, které nejde uspěchat. V samostatnosti karta ukazuje odpor přiznat si, že něco už skutečně skončilo, i když všechny signály tomu nasvědčují.",
    cta: "Chceš vědět, co Desítka mečů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "paze-mecu", name: "Páže mečů", section: "Malá arkána: Meče", appId: "paze-mece",
    intro: ["Mladá postava stojí na kopci s mečem pozvednutým a hlavou otočenou po větru, ostražitá, zvědavá, plná otázek. Karta bdělosti a zpráv, které je potřeba nejdřív ověřit."],
    up: "*Vzpřímeně* ve vztahu jde o zvědavost a otevřenou komunikaci, chuť ptát se a dostávat upřímné odpovědi. Pokud jsi sama, karta ukazuje, že se k tobě donesla zajímavá zpráva nebo pozornost, kterou stojí za to prověřit, než jí uvěříš naplno.",
    rev: "*Obráceně* se zvědavost mění v slídění. Ve vztahu jde o drby nebo kontrolování druhého způsobem, který spíš škodí důvěře. V samostatnosti karta varuje před tím, věřit informacím o někom novém, které jsi nezískala přímo od něj.",
    cta: "Chceš vědět, co Páže mečů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "rytir-mecu", name: "Rytíř mečů", section: "Malá arkána: Meče", appId: "rytir-mece",
    intro: ["Rytíř se řítí vpřed s mečem napřaženým, bez ohledu na bouři kolem sebe. Karta přímočaré, rychlé, možná až příliš zbrklé komunikace."],
    up: "*Vzpřímeně* ve vztahu jde o přímost, kterou situace potřebuje, konečně říct otevřeně, co si myslíš, i za cenu, že to nebude znít jemně. Pokud jsi sama, karta ukazuje setkání s někým přímým a rozhodným, kdo jde rovnou k věci, bez oklik.",
    rev: "*Obráceně* se přímost mění v bezohlednost. Ve vztahu jde o zbrklá slova řečená v hněvu, která se nedají vzít zpět. V samostatnosti karta varuje před typem, který mluví rychleji, než myslí, a nechává za sebou spoušť.",
    cta: "Chceš vědět, co Rytíř mečů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "kralovna-mecu", name: "Královna mečů", section: "Malá arkána: Meče", appId: "kralovna-mece",
    intro: ["Královna sedí na trůnu s mečem vzpřímeně vztyčeným, jasným pohledem hledící do dálky, nepodplatitelná lichotkami. Karta upřímnosti, jasného úsudku a nezávislosti."],
    up: "*Vzpřímeně* ve vztahu jde o schopnost vidět situaci bez sebeklamu a pojmenovat ji přesně, i když to není příjemné. Pokud jsi sama, karta ukazuje sílu nezávislosti, díky které si nenecháš namluvit víc, než co je pravda.",
    rev: "*Obráceně* se jasnost mění v chlad. Ve vztahu jde o přílišnou kritičnost nebo používání pravdy jako zbraně místo nástroje porozumění. V samostatnosti karta varuje před hořkostí z minulých zklamání, která ti brání vidět nové lidi bez předsudku.",
    cta: "Chceš vědět, co Královna mečů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "kral-mecu", name: "Král mečů", section: "Malá arkána: Meče", appId: "kral-mece",
    intro: ["Král sedí na trůnu s mečem v ruce, tvář nehnutá, rozhoduje na základě rozumu, ne emocí. Karta jasného úsudku a spravedlivé, i když chladnější autority."],
    up: "*Vzpřímeně* ve vztahu jde o partnera (nebo tebe samotnou), kdo dokáže řešit spory s chladnou hlavou a spravedlivě, bez zbytečné dramatičnosti. Pokud jsi sama, karta ukazuje přitažlivost k někomu racionálnímu a jasně uvažujícímu, kdo neslibuje víc, než může splnit.",
    rev: "*Obráceně* se rozum mění v manipulaci. Ve vztahu jde o používání logiky k tomu, aby měl navrch v každé hádce, na úkor citů druhého. V samostatnosti karta varuje před typem, který argumentuje chladně a přesvědčivě, ale bez skutečné empatie.",
    cta: "Chceš vědět, co Král mečů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "eso-pentaklu", name: "Eso pentaklů", section: "Malá arkána: Pentakly", appId: "eso-pentakly",
    intro: ["Ruka z oblaku podává zlatý pentakl nad zahradou plnou květin. Karta pevného základu, na kterém se dá stavět něco, co vydrží."],
    up: "*Vzpřímeně* ve vztahu jde o příležitost položit stabilní základ, ať formou společných plánů, nebo prostě rozhodnutím brát vztah vážně. Pokud jsi sama, karta ukazuje začátek, který má potenciál vyrůst v něco trvalého, ne jen v krátkou známost.",
    rev: "*Obráceně* zůstává příležitost nevyužitá. Ve vztahu jde o nejistý základ, na kterém se těžko staví cokoli trvalého. V samostatnosti karta ukazuje promeškanou šanci nebo nedostatek jistoty potřebné k tomu, pustit se do něčeho vážného.",
    cta: "Chceš vědět, co Eso pentaklů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "dvojka-pentaklu", name: "Dvojka pentaklů", section: "Malá arkána: Pentakly", appId: "dvojka-pentakly",
    intro: ["Postava žongluje se dvěma pentakly spojenými nekonečnou stuhou, v pozadí se houpou lodě na rozbouřeném moři. Karta udržování rovnováhy mezi vztahem a vším ostatním v životě."],
    up: "*Vzpřímeně* ve vztahu jde o schopnost sladit lásku s prací, rodinou a vlastními potřebami, i když se to někdy houpe jako lodě v pozadí. Pokud jsi sama, karta ukazuje, že žonglování s různými prioritami je teď normální, jen nezapomeň nechat prostor i pro to, co se v lásce může objevit.",
    rev: "*Obráceně* žonglování selhává. Ve vztahu jde o pocit zahlcení, kdy vztahu nezbývá dost pozornosti kvůli všemu ostatnímu. V samostatnosti karta ukazuje nedostatek rovnováhy, který ti brání otevřít se novému seznámení.",
    cta: "Chceš vědět, co Dvojka pentaklů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "trojka-pentaklu", name: "Trojka pentaklů", section: "Malá arkána: Pentakly", appId: "trojka-pentakly",
    intro: ["Tři postavy společně plánují stavbu katedrály nad výkresem, každá přispívá svou dovedností. Karta spolupráce a budování něčeho, co jeden člověk sám nepostaví."],
    up: "*Vzpřímeně* ve vztahu jde o týmovou práci na společném cíli, ať jde o domácnost, budoucnost, nebo jen o to, jak spolu řešíte každodenní věci. Pokud jsi sama, karta ukazuje, že budeš stavět vztah nejlíp s někým, kdo přináší dovednosti, které ty sama nemáš.",
    rev: "*Obráceně* spolupráce vázne. Ve vztahu jde o nerovnoměrné rozdělení úsilí, kdy jeden staví a druhý jen přihlíží. V samostatnosti karta varuje před hledáním partnera, který nechce přispívat vlastním dílem ke společné stavbě.",
    cta: "Chceš vědět, co Trojka pentaklů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "ctyrka-pentaklu", name: "Čtyřka pentaklů", section: "Malá arkána: Pentakly", appId: "ctyrka-pentakly",
    intro: ["Postava svírá jeden pentakl v náručí, druhý má na hlavě, dva pod nohama, jako by se bála, že o něco přijde. Karta lpění na jistotě ze strachu ze ztráty."],
    up: "*Vzpřímeně* ve vztahu jde o potřebu kontroly nebo strach z toho pustit, i city, drobet uvolnit. Pokud jsi sama, karta ukazuje, že možná držíš staré vzorce jistoty tak pevně, že nezbývá místo pustit dovnitř někoho nového.",
    rev: "*Obráceně* se sevřená pěst pomalu otevírá. Ve vztahu jde o uvolnění přehnané potřeby kontroly, větší štědrost v citech i v důvěře. V samostatnosti karta ukazuje ochotu riskovat jistotu samoty pro možnost něčeho víc.",
    cta: "Chceš vědět, co Čtyřka pentaklů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "petka-pentaklu", name: "Pětka pentaklů", section: "Malá arkána: Pentakly", appId: "petka-pentakly",
    intro: ["Dvě postavy kráčejí bosé sněhem kolem osvětleného okna kostela, aniž by si všimly, že dveře jsou otevřené. Karta pocitu vyloučení, i když pomoc je blízko."],
    up: "*Vzpřímeně* ve vztahu jde o pocit osamělosti nebo nedostatku podpory, i uprostřed vztahu, který by měl dávat oporu. Pokud jsi sama, karta ukazuje pocit, že jsi zvenčí, zatímco ostatní mají to, po čem toužíš, ačkoli pomoc a podpora jsou blíž, než si myslíš.",
    rev: "*Obráceně* se dveře konečně otevírají. Ve vztahu jde o přijetí podpory, o kterou jste dřív nepožádali. V samostatnosti karta ukazuje konec období nedostatku, i když pocit chladu může ještě chvíli doznívat.",
    cta: "Chceš vědět, co Pětka pentaklů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "sestka-pentaklu", name: "Šestka pentaklů", section: "Malá arkána: Pentakly", appId: "sestka-pentakly",
    intro: ["Postava rozdává mince žebrákům, v ruce drží váhy, které měří, kolik komu dát. Karta dávání a přijímání v rovnováze, nebo bez ní."],
    up: "*Vzpřímeně* ve vztahu jde o zdravou výměnu, kdy oba dáváte i přijímáte podle svých možností, bez pocitu dluhu. Pokud jsi sama, karta ukazuje štědrost, kterou dnes nabízíš i dostáváš, ať v přátelství, nebo v novém vztahu.",
    rev: "*Obráceně* se váhy vychylují. Ve vztahu jde o nerovnováhu v tom, kdo dává a kdo bere, nebo o dávání, ke kterému se váže nevyřčené očekávání. V samostatnosti karta varuje před vztahem, ve kterém štědrost slouží k udržení moci nad druhým.",
    cta: "Chceš vědět, co Šestka pentaklů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "sedmicka-pentaklu", name: "Sedmička pentaklů", section: "Malá arkána: Pentakly", appId: "sedmicka-pentakly",
    intro: ["Postava opřená o motyku hledí zamyšleně na keř obtěžkaný pentakly, hodnotí, jestli sklizeň stojí za dosavadní úsilí. Karta trpělivého vyhodnocování."],
    up: "*Vzpřímeně* ve vztahu jde o chvíli zhodnotit, kam jste za tu dobu společně došli, a jestli úsilí, které do vztahu vkládáte, přináší to, co jste čekali. Pokud jsi sama, karta radí k trpělivosti, výsledky tvého úsilí v lásce se možná ještě neukazují, ale rostou pod povrchem.",
    rev: "*Obráceně* dochází trpělivost. Ve vztahu jde o pocit, že do vztahu investuješ víc, než se ti vrací, a chuť to vzdát dřív, než uzraje sklizeň. V samostatnosti karta ukazuje frustraci z toho, že se výsledky nedostavují tak rychle, jak by sis přála.",
    cta: "Chceš vědět, co Sedmička pentaklů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "osmicka-pentaklu", name: "Osmička pentaklů", section: "Malá arkána: Pentakly", appId: "osmicka-pentakly",
    intro: ["Postava soustředěně vytesává pentakl za pentaklem, zdokonaluje své řemeslo opakováním a trpělivostí. Karta oddané práce na něčem, co se zlepšuje jen praxí."],
    up: "*Vzpřímeně* ve vztahu jde o vědomé budování dovednosti být dobrým partnerem, učení se skrze každodenní drobnosti, ne skrze velká gesta. Pokud jsi sama, karta ukazuje, že práce, kterou teď věnuješ sama sobě, se jednou promítne do zdravějšího vztahu.",
    rev: "*Obráceně* se řemeslo dělá napůl srdce. Ve vztahu jde o ulejvání se od skutečné práce na vztahu, opakování stejných chyb bez ochoty se poučit. V samostatnosti karta varuje před povrchním přístupem k seznamování, který nikam nevede.",
    cta: "Chceš vědět, co Osmička pentaklů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "devitka-pentaklu", name: "Devítka pentaklů", section: "Malá arkána: Pentakly", appId: "devitka-pentakly",
    intro: ["Postava stojí sama ve své zahradě, sokol na ruce, obklopená hojností, kterou si sama vypěstovala. Karta spokojenosti se sebou samou, která nepotřebuje záchranu zvenčí."],
    up: "*Vzpřímeně* ve vztahu jde o zdravou nezávislost uvnitř páru, každý má svůj prostor a přesto jste si blízcí. Pokud jsi sama, karta oslavuje přesně tohle: umíš si vytvořit pohodlný, bohatý život i bez partnera, a to je síla, ne náhradní řešení.",
    rev: "*Obráceně* se samostatnost mění v izolaci. Ve vztahu jde o přehnanou nezávislost, která brání skutečné blízkosti. V samostatnosti karta ukazuje závislost na tom, aby ti jistotu dodal někdo jiný, protože sama si ji zatím nedokážeš dát.",
    cta: "Chceš vědět, co Devítka pentaklů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "desitka-pentaklu", name: "Desítka pentaklů", section: "Malá arkána: Pentakly", appId: "desitka-pentakly",
    intro: ["Tři generace rodiny stojí pohromadě před branami domu, psi u nohou, symbol trvalého dědictví. Karta dlouhodobé stability a domova budovaného přes roky."],
    up: "*Vzpřímeně* ve vztahu jde o pocit trvalosti, spojení, které přesahuje jednotlivé chvíle a míří k něčemu, co vydrží roky. Pokud jsi sama, karta ukazuje, že směřuješ k typu vztahu, který jednou bude tvořit skutečný domov, ne jen dočasnou zastávku.",
    rev: "*Obráceně* je stabilita narušená. Ve vztahu jde o neshody kolem společné budoucnosti nebo rodiny, které otřásají tím, co se zdálo pevné. V samostatnosti karta ukazuje strach ze závazku na celý život, který tě brzdí přijmout vážnou nabídku.",
    cta: "Chceš vědět, co Desítka pentaklů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "paze-pentaklu", name: "Páže pentaklů", section: "Malá arkána: Pentakly", appId: "paze-pentakly",
    intro: ["Mladá postava drží pentakl oběma rukama a hledí na něj se soustředěným zájmem studenta, který se právě něco učí. Karta zvídavého, praktického zájmu."],
    up: "*Vzpřímeně* ve vztahu jde o ochotu učit se jeden druhého poznávat krok za krokem, bez spěchu. Pokud jsi sama, karta ukazuje nesmělý, ale upřímný zájem od někoho praktického a trpělivého, kdo postupuje pomalu, ale vážně.",
    rev: "*Obráceně* zůstávají plány jen na papíře. Ve vztahu jde o dobré úmysly, které se nikdy nepřevedou do skutečných kroků. V samostatnosti karta varuje před slibným zájmem, který nikdy nedojde k ničemu konkrétnímu.",
    cta: "Chceš vědět, co Páže pentaklů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "rytir-pentaklu", name: "Rytíř pentaklů", section: "Malá arkána: Pentakly", appId: "rytir-pentakly",
    intro: ["Rytíř sedí nehybně na statném koni uprostřed zoraného pole, trpělivý a nespěchající, ochotný čekat, dokud práce nebude hotová. Karta spolehlivosti, která nikam nespěchá."],
    up: "*Vzpřímeně* ve vztahu jde o partnera (nebo tebe samotnou), na koho se dá spolehnout, i když nepřináší velká gesta, jen stálou přítomnost. Pokud jsi sama, karta ukazuje, že se blíží nebo už je nablízku někdo pomalejší, ale spolehlivý, kdo dokazuje city činy, ne slovy.",
    rev: "*Obráceně* se stálost mění ve strnulost. Ve vztahu jde o nudu z rutiny nebo neochotu k jakékoli změně. V samostatnosti karta varuje před tím, čekat příliš dlouho na někoho, kdo se nikdy nehne z místa.",
    cta: "Chceš vědět, co Rytíř pentaklů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "kralovna-pentaklu", name: "Královna pentaklů", section: "Malá arkána: Pentakly", appId: "kralovna-pentakly",
    intro: ["Královna sedí v zahradě obklopená hojnou úrodou, králík jí pobíhá u nohou, pohodlná ve svém těle i ve svém domově. Karta pečující, praktické vřelosti."],
    up: "*Vzpřímeně* ve vztahu jde o schopnost vytvářet pohodlí a bezpečí, starat se o druhého prakticky i citově zároveň. Pokud jsi sama, karta ukazuje, že tvá vlastní schopnost postarat se o sebe je teď přesně to, co dělá vztah s tebou přitažlivý.",
    rev: "*Obráceně* se péče obrací dovnitř na úkor sebe sama. Ve vztahu jde o zanedbávání vlastních potřeb ve prospěch péče o druhého. V samostatnosti karta varuje před hledáním jistoty jen v tom, kolik toho pro druhé uděláš.",
    cta: "Chceš vědět, co Královna pentaklů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
  { slug: "kral-pentaklu", name: "Král pentaklů", section: "Malá arkána: Pentakly", appId: "kral-pentakly",
    intro: ["Král sedí na trůnu zdobeném hrozny, obklopen bohatstvím, které vybudoval vlastní trpělivou prací. Karta stability, spolehlivosti a štědrosti, která vychází z jistoty, ne z potřeby ohromit."],
    up: "*Vzpřímeně* ve vztahu jde o partnera (nebo tebe samotnou), kdo dává vztahu pevnou půdu pod nohama, klidně a bez dramatu. Pokud jsi sama, karta ukazuje přitažlivost k někomu stabilnímu, spolehlivému, kdo svou jistotu nemusí nikomu dokazovat.",
    rev: "*Obráceně* se stabilita mění v tvrdohlavost nebo v potřebu mít vše pod kontrolou. Ve vztahu jde o lpění na tom, jak by věci „měly\" fungovat, na úkor skutečné blízkosti. V samostatnosti karta varuje před typem, který jistotu předvádí navenek, ale citově zůstává nedostupný.",
    cta: "Chceš vědět, co Král pentaklů znamená přesně pro tvou otázku? Nech si karty vyložit od Nomi." },
];

export const LIBRARY_BY_SLUG: Record<string, LibraryCard> = Object.fromEntries(
  CARD_LIBRARY.map((c) => [c.slug, c])
);

// Karty stejné sady (interní prolinkování v1.6.2 §2) - nahrazuje dřívější
// náhodné „související karty".
export function sameSection(slug: string): LibraryCard[] {
  const me = LIBRARY_BY_SLUG[slug];
  if (!me) return [];
  return CARD_LIBRARY.filter((c) => c.section === me.section && c.slug !== slug);
}
